<?php

namespace App\Http\Requests;

use App\Http\Services\UserService;
use App\Rules\EmailNotFound;
use Illuminate\Foundation\Http\FormRequest;

class CreateLoginRequest extends FormRequest
{
    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => ['required', 'email', new EmailNotFound($this->userService)],
            'password' => ['required'],
        ];
    }
    public function messages()
    {
        return [
            'required' => 'Type your :attribute.',
            'email.email' => 'Email is incorrect.',
        ]; // TODO: Change the autogenerated stub
    }
}
